### ISSUE TITLE
Add starter content

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#116]
On a fresh install, the theme should generally end up matching [the demo site](https://2022.wordpress.net) by default: 

![Screen Shot 2021-10-15 at 10 01 26](https://user-images.githubusercontent.com/1202812/137500559-96f76e6e-00b1-41c5-86cd-a858f36e3605.png)

- Add a static homepage, with the `home` slug (so that it inherits our `page-home.html` template. The content of this page should match the demo above.
- Maybe a few posts to match the ones on the demo site.

In previous themes, we created starter content to help set folks up with this. Is this the best way to handle this for block themes?

**Comment by kjellr** [comment]
I opened a Gutenberg issue to explore this there as well: https://github.com/WordPress/gutenberg/issues/35680

**Comment by carolinan** [comment]
It was actually not so easy to get starter content to work even with the current "live preview" button before the theme is activated.

-I ended up using `page-slug.html` templates instead of the "home/frontpage/blog/"  because there is no conditional like in PHP where we can show single page content if it's set to show a page, and query when it is set to show posts.

Using a query and setting it to `inherit `is one way but it did not work for me since I wanted to show the full content for the page, and only show excerpt for the post list...

**Comment by mburridge** [comment]
Is it normal to have starter content? I don't recall ever installing a theme that added content to a site. Do you intend that the starter content will be "hard coded" into the .html files to be over-ridden by templates created in the editor? Personally I don't think I'd want that 'extra job', I want a theme to be blank so that I can just start adding content.

**Comment by carolinan** [comment]
Starter content is:

- Visible in the preview in the theme directory of WordPress.org, without it, you can only show the blog, not a custom homepage.
- Only available for users on fresh, empty WordPress installations.
- Optional, you can preview it and then choose to publish it.

**Comment by mburridge** [comment]
Thanks for that @carolinan. I've never used starter content before when I've built sites, but I've been[ digging in](https://make.wordpress.org/core/2016/11/30/starter-content-for-themes-in-4-7/) and learning more.

It seems to require the customiser. How is this going to work for an FSE theme?

And from a development point of view, would starter content still be hooked to `add_theme_support( 'starter-content', ....)`, or does it need to be implemented differently in an FSE theme?

**Comment by carolinan** [comment]
> It seems to require the customiser. How is this going to work for an FSE theme?

It does, but it is only the menu item that is removed. The starter content can still be previewed and activated via the themes screen, using the Live Preview button.

..That's what we need to figure out in https://github.com/WordPress/gutenberg/issues/35680

**Comment by mburridge** [comment]
Thanks @carolinan, so we're waiting on resolution of that issue before this one can be addressed? There's nothing to do here at the moment?
