### ISSUE TITLE
Block gap tight on headers and other visual elements

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentytwentytwo#120]
I am not sure if this needs a specific style for the header block in theme.json or the block gap itself increased - that would be a design decision (cc @kjellr). However, I noticed that the spacing is a little close when you have for example a cover block and gallery with header in-between:

![2021-10-15 at 20 07](https://user-images.githubusercontent.com/253067/137540119-1f245745-f326-4b8a-80ca-d7aee60043c6.png)

This was seen using Chrome.

**Comment by mburridge** [comment]
I think @karmatosed means the heading block rather than the header block, but in addition to the issue she reports the heading block spacing can be inconsistent, this example is after a gallery block. _(screenshots from Chrome, but looks identical in Safari and Firefox)_
![image](https://user-images.githubusercontent.com/20643925/138280042-879f2714-1adf-49e4-96dd-06a51ca0444b.png)

![image](https://user-images.githubusercontent.com/20643925/138280504-8f0e0a0f-59c4-4272-bf44-e11325f77f00.png)

**Comment by kjellr** [comment]
The spacing between blocks here largely comes from Gutenberg, and can often be adjusted via Margin or Padding. 

We aren't doing any specific per-block adjustments here in the theme at the moment (and I don't think we plan on adding any), so let's close this for now and open any specific issues upstream.
