### ISSUE TITLE
WP version compatibility check

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwentytwo#166]
Do we need a WordPress version check to assure compatibility with WP? Previous default themes, like Twenty Twenty-One, had a [`back-compat.php` file](https://github.com/WordPress/twentytwentyone/blob/trunk/inc/back-compat.php).

I assume that some features will be included in WP from 5.9 specifically for this theme, so we’ll need ‘at least 5.9’.

Would this (and the theme being a block-based theme) also allow us to remove block editor related `function_exists` checks, see: https://github.com/WordPress/twentytwentytwo/blob/8fd9d38a2f5791fbd3b07ad0cb880a2817242666/inc/block-patterns.php#L10

**Comment by jffng** [comment]
> Do we need a WordPress version check to assure compatibility with WP? Previous default themes, like Twenty Twenty-One, had a back-compat.php file.

I am not sure cc @aristath @carolinan, but it reminded me that currently there are some checks in Core for Gutenberg to be installed in order to use a block theme. I asked about removing those since 2022 is a block theme: https://core.trac.wordpress.org/ticket/54318#comment:3

> I assume that some features will be included in WP from 5.9 specifically for this theme, so we’ll need ‘at least 5.9’.

Yes, we should update the Requires at least line in `style.css`, but probably when we commit the theme to core since 5.9 is not released yet? 

> Would this (and the theme being a block-based theme) also allow us to remove block editor related function_exists checks

I think this + the discussion [here](https://github.com/WordPress/twentytwentytwo/issues/114#issuecomment-943704143) suggests we can remove those function_exists checks.

**Comment by kjellr** [comment]
This is something that should happen automatically for all block themes, so I'm going to close for now. We can track in this upstream issue: https://core.trac.wordpress.org/ticket/54342
