### ISSUE TITLE
Drop cap needs attention/styling

### ISSUE THREAD

**Issue by bgardner** [WordPress/twentytwentytwo#180]
**Describe the bug**
Per the screenshot below, the size/spacing of drop caps should be addressed.

**To Reproduce**
1. Go to editor, create paragraph.
2. Enable drop cap.
3. Save/publish and then look at back/front end.
4. See error.

**Expected behavior**
Better styling/spacing.

**Screenshots**
![image](https://user-images.githubusercontent.com/486261/139465114-a98ed642-a491-44ef-afcf-8d8e8c3fa9c7.png)

**Comment by kjellr** [comment]
I don't believe it's possible to finesse the drop cap styles through theme.json (maybe it should be?). But we can turn on/off the dropcap feature. 

Unless we have the ability to fix this through theme.json, I personally lean more towards just turning it off for the time being.

**Comment by bgardner** [comment]
Yeah, I realize there isn't a way through theme.json, and if the intent is to ship TT2 without any styles, your suggestion to turn it off would make the most sense. Mainly this was to acknowledge the way it looked and decide accordingly.

**Comment by colorful-tones** [comment]
I would vote to remove `dropCap` support.

**Comment by kjellr** [comment]
Sounds good, let's do it. I'll mark this as a Good First issue then. 👍

**Comment by Sandstromer** [comment]
This is strange. I didn't remember seeing an issue with drop cap, so tried it again with the same text as the screenshot. This is what I see on Windows.

![2022-drop-cap](https://user-images.githubusercontent.com/76742815/139664464-9c9d6e7c-7db0-4313-ad94-f39124267f6f.png)

Could the issue be something to do with the Mac system font?

**Comment by kjellr** [comment]
Yeah, I think it's likely due to that font in the stack (and is potentially present for others too). In any case, I still think it's ok to remove this feature for now since it's not core aspect of the theme design. @colorful-tones has helpfully opened [an issue upstream](https://github.com/WordPress/gutenberg/issues/36122) to introduce greater control over dropcaps, so maybe we can add it back in as an enhancement post-release. 👍
