### ISSUE TITLE
Will menus be supported?

### ISSUE THREAD

**Issue by bgardner** [WordPress/twentytwentytwo#181]
**Description**

I realize that currently the theme menu is built to pull in the page list via header.html. Is there a plan to support more than that? I ask because I noticed there was not a Menu link under Appearance, and I can easily see folks wanting to control their menus. (Either by reordering/removing pages, including links to social media, etc.)

**Comment by bgardner** [comment]
Also worth nothing that Menus _are_ accessible via the Customizer still.

**Comment by colorful-tones** [comment]
@bgardner I believe that the Navigation block is maturing (as we speak) in Gutenberg land to be the main point of editorial flow in Full Site Editor experience to manipulate and customize a menu's items. I know that the Navigation block is one of the main features slated for 5.9. 🤔 

This seems to be the Tracking Issue for Navigation Block in 5.9: [A Lighter Navigation Block Experience #34041](https://github.com/WordPress/gutenberg/issues/34041), which might help shed some light.

It is definitely worth testing and investigating the Navigation block usage in TwentyTwentyTwo. 👍

**Comment by kjellr** [comment]
> I realize that currently the theme menu is built to pull in the page list via header.html. Is there a plan to support more than that?

That page list is just the default, and it can be edited inline via the Navigation block. The theme is not planning to provide any theme-specific functionality for menus. 

This Gutenberg feature is undergoing heavy iteration during the Gutenberg 11.9 cycle, so I suggest taking a look at these issues if you're interested in learning more: 

https://github.com/WordPress/gutenberg/pull/35746
https://github.com/WordPress/gutenberg/issues/35947

Since this functionality is managed upstream, I'm going to close this issue for now.
