### ISSUE TITLE
Next and previous post navigation

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#193]
There is no next and previous navigation between single posts, is this intentional?

**Comment by kjellr** [comment]
Yes, that was a design decision. I liked the simplicity of not having it, and I don't think it's truly necessary. If folks wanted to add it in, it should be relatively simple to do so with the Site Editor. 

I'll leave this open for a bit though in case folks have strong opinions otherwise that they'd like to share.

**Comment by carolinan** [comment]
I think it is fine for the theme to not have it.

The problem is that now the post navigation link block is still experimental, so no other themes can have it either unless they require Gutenberg.

**Comment by kjellr** [comment]
Yeah, those blocks should not be marked as experimental. Thanks for opening [the issue upstream](https://github.com/WordPress/gutenberg/issues/36134). 👍
