### ISSUE TITLE
Mobile Hamberger menu is not clickable 

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentytwo#228]
Tested with the latest WP version 5.8.2 and Gutenberg version 11.9.0, the mobile menu is not clickable. Also, a mobile menu should work with keyboard navigation too. 

Make a menu and switch the browser in mobile view and text the mobile menu.

**Comment by jffng** [comment]
Hi there, I'm unable to reproduce this in the environment shared. Here are my results: 

https://user-images.githubusercontent.com/5375500/141331456-5b2286b6-ff49-48c4-a34d-f933cbca71e1.mp4

If there is indeed an issue, it is more likely due to the navigation block itself and may be better directed upstream in Gutenberg. To verify it may be worth testing with [emptytheme](https://github.com/WordPress/theme-experiments/tree/master/emptytheme) to see if the result is the same.

**Comment by chthonic-ds** [comment]
@kafleg does https://github.com/WordPress/gutenberg/issues/35686 describe the issue you're seeing?

**Comment by kafleg** [comment]
Hi
I see this issue time and again. It was fixed before in Gutenberg and again I see it again. 
I am using the Edge browser. But not working in chrome either. And I used the default menu block. The content is for testing purpose.

**Comment by kjellr** [comment]
Either way, I think this is an upstream bug and not something specific to the theme — Twenty Twenty-Two just adds the search block and doesn't modify it in anyway. I think it would be ok to close here and open an upstream bug if you're seeing issues.

**Comment by jffng** [comment]
> I think it would be ok to close here and open an upstream bug if you're seeing issues.

Agreed, if the issue persists I believe it should be addressed upstream in the navigation block / Gutenberg. Thanks.
