### ISSUE TITLE
Question: OK to have multiple H1 headings per page?

### ISSUE THREAD

**Issue by Sandstromer** [WordPress/twentytwentytwo#233]
**Description**
I noticed the Site Title in the header is a H1 heading, and also the Query Title in the index template is also a H1 heading.

When viewing an archive/category/author etc there are two H1 headings on the page.

The Post Title blocks within the Query loop in the archive are H2.
If the Query Title was changed to H2, then the Query Loop Post Title's should be changed to H3?

This would be OK for viewing archives, but then the main home index would be missing a H2 Query Title, and would go from Site Title H1 to the Query Loop Post Title's H3.

Hope I've managed to explain my thinking okay here, and not sure whether I'm fussing over something that should not really be of concern?

The Site Title could be changed to paragraph but I guess that would not be deemed correct?

**Comment by kjellr** [comment]
In general, we shouldn't. Oftentimes, the way this works for themes is: 

- The Site Title is a `h1` on the homepage, or any page without a distinct title. 
- The Site Title is a `p` on pages where we expect there to be a distinct H1. 

Since these are pulling from the same `header.html` template part, we can't have it dynamically change that way. For now, it's calling the Site Title a `h1` everywhere, because this way we know we'll always have at least one H1 on the page. We _could_ change it to a `p`, but then I imagine we'll have some pages where there is no `h1` at all (like the `index.html` page when it's used for Blog Posts). 

If anyone has suggestions, please share!

Related: https://github.com/WordPress/twentytwentytwo/issues/82

**Comment by kafleg** [comment]
These days Google doesn't mind if any page has multiple H1 tags, but standard practice is to make sure H1 is assigned to the main title of that page.

Reference: https://www.youtube.com/watch?v=zyqJJXWk0gk

**Comment by kjellr** [comment]
We had [a discussion about this in #core-themes the other day](https://wordpress.slack.com/archives/C02RP4VMP/p1636990136197100?thread_ts=1636989618.188800&cid=C02RP4VMP) (signup required to view the link). I'm going to surface some of the discussion to add to what's here in the ticket: 

- WCAG Guidelines do not prohibit more than one H1 per page. 
- The `accessibility-ready` guidelines for the Theme Directory are not strictly the WCAG guidelines though. [Those guidelines _do_ require no more than one H1 per page](https://make.wordpress.org/themes/handbook/review/accessibility/required/#headings). 

We need to follow those guidelines, so unless those are changing, I suggest we: 

- Keep the post/page titles as H2s (which seems weird to me, honestly). 
- On the archive template, change the Archive Title to a H2.
- On the archive template, change the post titles to H3s. 

Related: https://github.com/WordPress/twentytwentytwo/pull/249 #250

**Comment by SGr33n** [comment]
Hi!
I just entered the discussion :)
My two cents, the best practice should be:
On single post and pages having the post/page title as h1
On archive pages having the archive title as h1
On the home page having the site title as h1

This is also the defalut behavior for the latest Defalut WordPress themes.

**Comment by aristath** [comment]
I think it's the requirements that need to change in this case....

**Comment by kjellr** [comment]
> On the home page having the site title as h1

The root of the issue here is that the Site Title is part of a non-dynamic template part, and doesn't know which template it's in. So we're stuck with it either being a h1 all the time, or being a paragraph all the time. Both cases will end up with some non-ideal situations. It might be possible for Gutenberg to make the Site Title tag dynamic, but since users can technically change the heading level of any block on the page, I worry that it might get too complicated and/or make things worse. 

As @aristath noted, I think in this case it might be that the guidelines need to change, especially since they're already more strict than the WCAG guidelines.

**Comment by SGr33n** [comment]
@kjellr you're right, but is also true that could be enough to distribute the theme working with a correct behavior, then the users can change it. As I can see the page title have a "level" parameter optional, with an h2 default value. The block could define a default value according to the page type. This could also happen on the site name.
Regarding the logo / site name, I see at the moment difficult (maybe I'm wrong) to define a single tag as link for both logo and site title at the same time. I would build a new block called "Site branding" (that's the name that the related part of the theme had on the latest Twenty Theme series). This could incoroprate the Logo, the Site name and the tagline. Then the block could have showTitle, showDescription and showLogo parameters as happen on the post-author block where we can define if show or not the avatar. That block could allow users to define a tag for site title and for the logo at the same time as the link.

**Comment by kjellr** [comment]
> I think it's the requirements that need to change in this case....

@carolina + @kafleg, do you have any thoughts on whether changing the requirements is a good idea or not?

**Comment by joedolson** [comment]
The reason the theme accessibility-ready guidelines are stricter than WCAG is mostly for clarity: the guidelines were written to be easily testable and explicit.

The point being that we couldn't provide extensive accessibility training to theme reviewers, so we needed the rules to be as narrow as possible. As long as we update the guidelines in a way that still meets that criteria, I think it would be fine.

**Comment by pattonwebz** [comment]
I can take the first pass at updating the wording of this specific guideline and collaborate with a11y team to ensure that the wording still meets the criteria.

**Comment by kjellr** [comment]
Thank you both for the guidance and help here!

**Comment by kjellr** [comment]
Based on the discussion and resulting actions above, plus the fact that #249 and #250 have been merged in, I'm going to mark this issue as resolved. We can always re-open if we feel the need to reconsider. 

Thanks for the input everyone!

**Comment by sabernhardt** [comment]
This probably belongs in a separate issue, but the _footer_ templates also include the site title as an H1 heading.

**Comment by kjellr** [comment]
Thanks, @sabernhardt! That was unintentional. There's a fix over in https://github.com/WordPress/twentytwentytwo/pull/293.
