### ISSUE TITLE
Update "Footer with navigation and copyright" and "Footer with social links and copyright" patterns to use the site title block

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentytwo#255]
**Describe the bug**

Could this be updated to include the site title block instead of a hard coded text? I think it would be possible now with the row block available?

```
<!-- wp:paragraph {"align":"center","style":{"typography":{"fontSize":"16px"}}} -->
<p class="has-text-align-center" style="font-size:16px">' . esc_html__( '© Site Title', 'twentytwentytwo' ) . '</p>
<!-- /wp:paragraph --></div>
```

**Comment by kjellr** [comment]
_Technically_ yes it can be done this way. Here's example markup: 

```
<!-- wp:group {"layout":{"type":"flex","justifyContent":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center","style":{"typography":{"fontSize":"16px"}}} -->
<p class="has-text-align-center" style="font-size:16px">©</p>
<!-- /wp:paragraph -->

<!-- wp:site-title {"isLink":false,"fontSize":"small"} /--></div>
<!-- /wp:group -->
```

But it ends up looking wrong because the blockGap is far larger than a normal space: 

<img width="230" alt="Screen Shot 2021-11-19 at 10 52 08 AM" src="https://user-images.githubusercontent.com/1202812/142652040-42778cdd-a5a8-4cd2-b1af-17e494b27729.png">

I don't think we can get that fixed without a solution to https://github.com/WordPress/gutenberg/issues/35778.

**Comment by carolinan** [comment]
What about using the real site title instead of the hardcoded words, since these are PHP patterns? 🤔

**Comment by kjellr** [comment]
Hmm that's a good thought. My concern is that it won't stay in sync if you changed your site title though. Since the user would've already seen this intelligently populate, they'd probably think of that as a bug. 🤔

**Comment by kjellr** [comment]
Now that we're nearing release, I'm going to close this issue. If anyone has further thoughts to share on this topic, feel free to open up [a new issue on Trac](https://core.trac.wordpress.org/newticket?component=Bundled+Theme).
