### ISSUE TITLE
2022.wordpress.net is empty

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#268]
**Description**

2022.wordpress.net doesn't render anything, cc @kraftbj.

**Comment by kraftbj** [comment]
I'm looking. There are no PHP errors and other themes render fine, so it seems to be something with 2022 specifically.

**Comment by kraftbj** [comment]
I think it is due to this:

https://github.com/WordPress/twentytwentytwo/pull/265#issuecomment-982945635 cc: @kjellr 

The site runs stable Gutenberg, but sounds like the theme (at least what is in this repo) is now expecting `trunk` Gutenberg? Is there a simple way to track trunk or should we just wait until 12.1 comes out? The site keeps Gutenberg auto-updated to the latest version, so it'll self-resolve within 12 hours of 12.1 going stable.

**Comment by kraftbj** [comment]
For now, I switched to the `v0.4.0` tag so the site will load. Once Gutenberg 12.1 ships, I'll switch back to `trunk` to confirm that 265 was indeed the issue.

**Comment by kjellr** [comment]
Yeah, that sounds like the issue, thanks @kraftbj! We can keep this open until 12.1 ships just to confirm.

**Comment by kraftbj** [comment]
12.1 of Gutenberg shipped. I updated it on the demo site and reset the `twentytwentytwo` folder to track `trunk` again. It seems to be working 👍🏼 .

I think this issue can be closed now.

**Comment by kjellr** [comment]
Yep! It works. Thanks @kraftbj!
