### ISSUE TITLE
Design of Post Comment button in single post

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentytwo#281]
Installed beta 2 version of 5.9 and preview the single post page. The design of the button is not good. 
Do we have a design idea for that button? 

* Install WordPress 5.9 beta 2 
* Preview the Hello World post
* Scroll down to the comment section. 
![image](https://user-images.githubusercontent.com/13062231/145151756-7a48065b-8e3f-49e7-814b-c1fcda46c661.png)

Also, logout the site and see the comment section on the front page.
![image](https://user-images.githubusercontent.com/13062231/145151839-2cf6e9d6-95e5-44fb-86b9-cb6d706101d4.png)

**Comment by kafleg** [comment]
@bijayyadav was interested to contribute to the theme. You can check and follow up.

**Comment by bijayyadav** [comment]
I would like to fix and commit, is there any recommendation for the design? If I get the design, I can fix and commit.

**Comment by kjellr** [comment]
This should not be fixed in the theme. It looks like there's a mismatch between a change in Core and something in the Gutenberg plugin. In Gutenberg, the button carries a `wp-block-button__link` class, which lets it inherit the default button appearance, but this is missing in core.

cc @noisysocks can you help pinpoint what's missing here?

Gutenberg|Core
---|---
<img width="702" alt="Screen Shot 2021-12-08 at 7 50 24 AM" src="https://user-images.githubusercontent.com/1202812/145211271-26d53765-7cb0-4aa0-a609-35d52853febc.png"><img width="695" alt="Screen Shot 2021-12-08 at 7 50 39 AM" src="https://user-images.githubusercontent.com/1202812/145211276-4769d8f7-9254-45a0-a8e2-983742c8de53.png">|<img width="732" alt="Screen Shot 2021-12-08 at 7 49 52 AM" src="https://user-images.githubusercontent.com/1202812/145211286-3819e73f-c231-4773-9c47-7187bacd806e.png"><img width="720" alt="Screen Shot 2021-12-08 at 7 50 07 AM" src="https://user-images.githubusercontent.com/1202812/145211292-f9f8bbb1-525c-4224-8f1a-6e94d18f9676.png">

**Comment by noisysocks** [comment]
It looks like this was fixed in https://github.com/WordPress/gutenberg/pull/31338 for the Post Comments Form block, but the Post Comments Form block is not included in WP 5.9. Instead, we include Post Comments block which has a form in it. I think therefore we'll need to make a similar change to https://github.com/WordPress/gutenberg/pull/31338 but for the Post Comments block.

@aristath: Do you think you could open a Gutenberg PR for that and put the backport label on it?

**Comment by aristath** [comment]
PR in https://github.com/WordPress/gutenberg/pull/37245 👍

**Comment by kjellr** [comment]
Thanks for the quick investigation and fix!

**Comment by kafleg** [comment]
Marking this ticket as closed. The issue is fixed. We can reopen later if necessary.
