### ISSUE TITLE
show the legend of the featured image

### ISSUE THREAD

**Issue by naunha** [WordPress/twentytwentytwo#285]
How can I show in posts, the description and caption of the highlighted image, below it? (no plugin)

Thank you very much for any help.

**Comment by kjellr** [comment]
Hi, @naunha! Since Twenty Twenty-Two is a block theme, its functionality is powered by what the Block Editor provides. At the moment, the Featured Image block does not support displaying a description or caption, but if you think that would be helpful, I suggest you [open a feature request in the Gutenberg repository](https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Feature_request.md). If your feature is added there, it will be available to any block theme. 

Since there's nothing we can do in Twenty Twenty-Two itself, I'm going to close this ticket for now, but thanks for the question!
