### ISSUE TITLE
Close button placement does not align with the placement of the menu button

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#292]
By default, when you click the menu button on a smalls screen, the location of the close button is slightly different than the location of the menu itself: 

![tt2-menu](https://user-images.githubusercontent.com/1202812/145615536-aeb48911-4754-454f-be24-38f064bfd25c.gif)

This is a little annoying, and it would be great if we could fix it. However, it's complicated by the fact that we have no idea where the menu button is actually going to be located. If the site title were stacked, then the menu button will move down from here slightly. And for what it's worth, the user can place a menu button in the footer, or all the way over to the left, etc. So there's no way we'd be able to match it exactly every time, and we probably wouldn't even want to. 

But still, this state where it's _almost_ in the same place feels like a bug. 

I'm not sure there's a good solution to this, and if there were it would likely need to happen upstream. But I'm opening the issue here to start discussion. 

cc @jasmussen, since I bet you've thought about this already at some point.

**Comment by jasmussen** [comment]
It does feel like a bug! I think there's a long term fix for this which we also need to enable the burger icon transforming into the close icon. But nearer term, I wonder if there aren't some margins we can inherit. In any case, I'll take a look first thing Monday.

**Comment by jasmussen** [comment]
As promised, I took a look. Unfortunately it's not quite as easy as I had hoped, and there are a few reasons for that. First off, this is how close I got:

![close](https://user-images.githubusercontent.com/1204802/145794567-da59cee8-3a52-4cc3-b0f8-7e3bf07bc4b5.gif)

Vertically, that should be right. But horizontally, it's not. In my test, I was able to inherit the top padding of the container, this one:
<img width="575" alt="Screenshot 2021-12-13 at 11 19 17" src="https://user-images.githubusercontent.com/1204802/145794746-40e0fcf0-1576-4f34-8f9b-5b39565735ee.png">

<img width="616" alt="Screenshot 2021-12-13 at 11 19 25" src="https://user-images.githubusercontent.com/1204802/145794771-1c44c575-96ee-49e6-b2ca-dbb588d127a7.png">

But as you can also see, the horizontal padding I was not able to inherit, because in TT2 it's applied to a parent container. 

The clamp based paddings make this a bit more visible:
![the fuller picture incognito](https://user-images.githubusercontent.com/1204802/145795093-3035cc1e-3e0c-46c8-b93c-157c93160246.gif)

Then of course there's the wp-adminbar throwing a wrench into things:
![the fuller picture](https://user-images.githubusercontent.com/1204802/145795128-7d13d2f7-ec10-4277-8487-6e432d6b394b.gif)

Even in putting together this proof of concept PR to test things, I had to hack around and apply the padding inheritance conditionally, lest the burger icon itself received padding. That's fixable, but it also means we're starting to optimize a bit for a particular type of markup, which makes me a bit apprehensive about moving too far in that direction.

I know this isn't what you want to hear, but if you add a little custom CSS, this is easily within your control:
![custom css](https://user-images.githubusercontent.com/1204802/145796354-5274408b-44b9-4cc4-9a6e-356b73bed174.gif)

I need to make a small PR to adjust how the close button and menus are positioned (and fix that gnarly vertical alignment bug that keeps reappearing), but the CSS can be as simple as this:

```
.wp-block-navigation__responsive-container.is-menu-open {
	padding-top: var(--wp--custom--spacing--small, 1.25rem);
	padding-bottom: var(--wp--custom--spacing--large, 8rem);
	padding-right: var(--wp--custom--spacing--small, 1.25rem);
	padding-left: var(--wp--custom--spacing--small, 1.25rem);
}
```

I know you were hoping otherwise. But this feels like an appropriate use of theme styles to me. If need be you can add a comment about coming back to this when we have full global styles configuration of the contents of the modal. What do you think?

**Comment by jasmussen** [comment]
I created https://github.com/WordPress/gutenberg/pull/37323 to make it easier to style the padding of the modal as suggested above. 

Edit: you should even be able to apply a `max-width: 1000px;` to the inner container, making the X button perfectly overlay the close button regardless of the clamp based rules.

**Comment by kjellr** [comment]
> Edit: you should even be able to apply a max-width: 1000px; to the inner container, making the X button perfectly overlay the close button regardless of the clamp based rules.

Cool, we'll spin up a quick PR to try this out.

**Comment by jasmussen** [comment]
Depending on how that PR goes, do let me know. If it goes well, I'll apply the "backport" label for https://github.com/WordPress/gutenberg/pull/37323 for TT2 to rely on.
