### ISSUE TITLE
Inappropriate padding left/right being applied within pattern BlockPreview

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentytwo#330]
**Describe the bug**
It looks like the left/right padding that we've applied to ` .editor-styles-wrapper > .is-root-container` is now negatively affecting the BlockPreviews, making fullwidth patterns not appear fullwidth anymore. 

**Expected behavior**
Fullwidth patterns display as such in the Pattern Library

**Screenshots**
![CleanShot 2022-01-10 at 19 51 27@2x](https://user-images.githubusercontent.com/1813435/148862204-7d853a26-3c6b-4f82-95c8-9f12fe5466ed.png)
![CleanShot 2022-01-10 at 19 52 33@2x](https://user-images.githubusercontent.com/1813435/148862239-224dac12-74c5-49ba-ba44-24fc25cd50dc.png)

**Additional context**
WP 5.9 RC

**Comment by richtabor** [comment]
After looking into this further, it may be because the top-level align `full` block is not getting the `.wp-block[data-align="full"]` wrapper div within BlockPreview. I'm not sure if this in intentional — @youknowriad do you know?

When a fullwidth pattern is added to the page, it does indeed get the wrapper, which TT2 has [negative margin](https://github.com/WordPress/twentytwentytwo/blob/trunk/style.css#L110-L113) applied to remove the left/right padding effectively. 

**Within the BlockPreview:**

<img width="1133" alt="CleanShot 2022-01-10 at 21 13 19@2x" src="https://user-images.githubusercontent.com/1813435/148869435-35980db2-3bec-493c-81d2-1b9456b22489.png">

**Added to the editor:**

![CleanShot 2022-01-10 at 21 16 12@2x](https://user-images.githubusercontent.com/1813435/148869696-61ca721a-c53e-4d95-b752-4c462631f8c9.png)

**Comment by kjellr** [comment]
I could be wrong here, but I think these previews actually behave the same way that the site editor behaves, in that "inherit default layout" isn't set to true for the main container. And that results in direct "alignfull" children not going 100% full-width. 

For our header/footer patterns, I added an extra (empty) Group block wrapper to solve for this and ensure they show up full-width in the site editor (and in previews):

<img width="895" alt="Screen Shot 2022-01-11 at 9 24 50 AM" src="https://user-images.githubusercontent.com/1202812/148960722-bed35c28-7e82-4b13-b687-56cb1f018610.png">

I didn't bother doing that for the other patterns though, which are likely going to be added directly in posts and pages instead. I'm not really sure the best way to solve for this, especially because I don't want to make too many changes that are tailored to the custom CSS layout solution in the Twenty Twenty-Two — I expect that to go away in favor of a Gutenberg-based solution instead eventually.

**Comment by richtabor** [comment]
Hmm, seems like adding an extra group block does resolve it, but that's not ideal for sure :/
