### ISSUE TITLE
Issue with the content's width of the Cover block

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentytwo#332]
**Describe the bug**
A month ago, I opened this ticket https://github.com/WordPress/gutenberg/issues/37036  regarding the fact that it's impossible to set the width of the cover inner blocks. Currently, when using the Twenty Twenty-Two theme (or any block theme), the text inside the Cover blocks is full-width, thus not readable when using a full-width cover. 

As it appears that no fix will be included in the WordPress 5.9 release, maybe the theme could include a CSS fix as the cover block is not usable anymore.

**To Reproduce**
1. Inside the page editor, insert a Cover block and set it to full-width.
2. Insert some long text.
3. See that the text is full-width.

**Expected behavior**
IMO, a user should be able to use the Cover block out of the box without having to add a group inside the cover to fix this issue.

**Screenshots**
![cover-full](https://user-images.githubusercontent.com/56188815/148962147-4a0687a4-f63b-454f-9d42-391e98080baf.jpg)

**Comment by kjellr** [comment]
Thanks for filing the issue, @briceduclos. In general, the approach to Twenty Twenty-Two has been to avoid doing theme-specific fixes for Gutenberg issues whenever possible. Now that we're so close to release, I'm personally even more hesitant to add in that sort of code.  

It looks like there's [a PR here](https://github.com/WordPress/gutenberg/pull/37662) to get this working, so that's the best bet moving forward. I understand it's frustrating that this won't get in for the 5.9 release, but maybe it can be added to a minor release afterwards. Plus, once it's fixed in Gutenberg, it'll work for _all_ block themes. 

I'm going to close this issue for now, but we can keep discussing if you'd like. Thanks again for the report!

**Comment by sabernhardt** [comment]
@briceduclos Could you set up an account on WordPress.org and [connect your GitHub username](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/) so your name will be listed on the WordPress Credits page for the 5.9 release?
