### ISSUE TITLE
Add gigantic and colassal font sizes to typography.fontSizes

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentytwo#37]
Is the a particular reason why the `gigantic` and `colossal` font sizes were omitted from `typography.fontSizes`? Or were they just looked over? 

They are added as ([custom css properties](https://github.com/WordPress/twentytwentytwo/blob/trunk/theme.json#L38-L39)), but not  accessible within the font size UI.

**Comment by kjellr** [comment]
Yeah! The reason I left those out was to restrict us to using the same exact 5 font size names that ship with core by default (small, normal, medium, large, huge). Since there's no core-adopted naming paradigm beyond that I thought it was safer to keep these extra two values out separate for now. 

I'm happy to reconsider, but I think this sets us up better to change them later on if we need to. Once folks have a content using `has-font-size-colossal` in it, it will be tougher to update cleanly.

**Comment by jffng** [comment]
I'm in favor of standardizing the fonts sizes to the five that ship with core, and use specific font size values for `gigantic` and `colossal` in the patterns. Okay if we close this one @richtabor ?
