### ISSUE TITLE
Ensure full-width items within post content go full-width

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#5]
_Flagging this issue from https://github.com/WordPress/twentytwentytwo/pull/4#discussion_r721786880 to follow up later:_ 

Due to some left/right padding rules, `alignfull` items within posts and pages do not actually extend to the full width of the page:

<img width="1272" alt="Screen Shot 2021-10-04 at 7 40 10 PM" src="https://user-images.githubusercontent.com/1202812/135938627-d5c08a48-9164-4ae2-b3a3-497760e674e2.png">

We should (hopefully) find a way to allow for full-width items to go all the way to the screen edges, while still retaining a similar measure of left/right padding for the header and other non-full-width items.

**Comment by pattonwebz** [comment]
The most common technique I have seen used to do this is with CSS similar to this:

```
.alignfull {
	margin: 2rem calc(50% - 50vw);
	max-width: 100vw;
	padding: 1rem 2rem;
	width: 100vw;
}
```

That has some implications on chrome where it can cause a horizontal scroll bar due to chrome (possibly all webkit browsers) not accounting for the vertical scrollbar when it calculates what 100vw is. I think it's worth exploring if this will be suitable and if the kinds with chrome can be worked out.

**Comment by kjellr** [comment]
Closing to consolidate this issue into https://github.com/WordPress/twentytwentytwo/issues/234.
