### ISSUE TITLE
Homepage content & user experience

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/twentytwentytwo#60]
Perhaps I'm not familiar enough with Block Theme/FSE, but as an everyday editor I would be confused by the following dilemma. I created a new empty WordPress site in Local. I have TwentyTwentyTwo theme activated and latest Gutenberg.

I already have **44 posts** I've generated using [FakerPress plugin](https://wordpress.org/plugins/fakerpress/). I visit my site's homepage and see: "Welcome to WordPress. This is your first post. Edit or delete it, then start writing!" Here, the confusion begins.

My first instinct is to check my **Settings** > **Reading** and verify that "Your homepage displays: Your latest posts". This is contradicting what I'm seeing on the homepage though. 😕 

It is likely this is a user experience improvement for Gutenberg Full Site Editing experience, and just wondering if I'm missing something?

![Screen Shot 2021-10-07 at 4 42 39 PM](https://user-images.githubusercontent.com/405912/136459794-3daec021-e733-4b97-9eee-4dbf1bf9eef4.png)

![Screen Shot 2021-10-07 at 4 41 19 PM](https://user-images.githubusercontent.com/405912/136459494-71af2382-b7fe-432b-937a-670fa0e26bc5.png)

**Comment by colorful-tones** [comment]
I've gone ahead and installed, activated WordPress Beta Tester and I'm now running WordPress 5.9-alpha-51894 and still the same experience. 🤔

**Comment by colorful-tones** [comment]
Furthermore, as a user I'm on my homepage and seeing the "Welcome to WordPress. This is your first post. Edit or delete it, then start writing!" message and I'm confused. So, I proceed with thinking that maybe I need to add a Query Loop block to the page. So, I click "Edit site" in WP Admin Bar, and I'm in the Site Editor and see: "This is for placeholder content." and I'm not able to add a Query Loop block within the main content. Now, I'm _super_ confused, and likely frustrated.

![Screen Shot 2021-10-07 at 4 55 23 PM](https://user-images.githubusercontent.com/405912/136461038-6ba9f331-cd82-418f-aaa0-3e48aa9c919a.png)

**Comment by colorful-tones** [comment]
Also, the "Welcome to WordPress. This is your first post. Edit or delete it, then start writing!" gives me little actionable items. The "Edit" and "delete" are not links and there is not even an option to "Edit Page" in the WP Admin Bar (just "Edit Site", but it says and implies to _edit my first post_. 🤷‍♂️

**Comment by Sandstromer** [comment]
I am able to recreate this issue with the same fresh install default 'Reading' settings.

It looks like this is caused by the theme's `front-page.html` template, which only contains the Post Content block `<!-- wp:post-content {"layout":{"inherit":true}} /-->`, rather than the Query Loop block that is found in the `index.html` template.
The consequence of this is that the full content of single oldest post (usually the default Hello World! post) is displayed on the front page, rather than the expected latest posts.

Not sure if this is a theme issue or a deeper core/Gutenberg issue, as I would have thought that themes should be able to bundle a `front-page.html` template and expect to have this template used only where the user has defined a static homepage.

**Comment by kjellr** [comment]
> Not sure if this is a theme issue or a deeper core/Gutenberg issue, as I would have thought that themes should be able to bundle a front-page.html template and expect to have this template used only where the user has defined a static homepage.

I think the issue here is template hierarchy, and to be honest, [it always been confusing](https://wp-mix.com/difference-between-home-front-page-php/). 😅 

I _think_ the solution is that we shouldn't actually be using `front-page.php` here, but off the top of my head I'm not sure the correct template(s) we need to use instead. Might also be a Gutenberg issue though.

**Comment by kjellr** [comment]
> I think the solution is that we shouldn't actually be using front-page.php here, but off the top of my head I'm not sure the correct template(s) we need to use instead. Might also be a Gutenberg issue though.

It's `home.php`. 😄 #69 should take care of this.

**Comment by Sandstromer** [comment]
It's tricky because in a classic php theme you could do something like have a conditional check for `show_on_front`, use a dedicated front page template if true, and use the index or home template if not true.

In block themes we lose this ability and have to follow the hierarchy.

TT1 Blocks theme has a `page-home.html` template that the user can select, but as I understand it there doesn't seem to be any way of using conditionals within a block theme.

**Comment by kjellr** [comment]
Yeah, I just reworked #69 to use a `page-home.html` and avoid using a `home.html` entirely. I think that's our best bet for the moment.

**Comment by pattonwebz** [comment]
> Yeah, I just reworked #69 to use a `page-home.html` and avoid using a `home.html` entirely. I think that's our best bet for the moment.

Does using `page-home.html` then rely on the slug of the page being `home`?

**Comment by kjellr** [comment]
[Yeah](https://github.com/WordPress/twentytwentytwo/pull/69#issuecomment-938724308), which isn't ideal.

**Comment by pattonwebz** [comment]
Not ideal but I don't have any better ideas for an alternative either :(

What is kinda nice though is showcasing more granular use of template hierarchy - which isn't often seen in themes and I don't think ever used in a default theme :)
