### ISSUE TITLE
Related Gutenberg Issues and PRs 

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentytwo#75]
Let's use this issue to track and prioritize issues that are needed for the theme. 

**Must have**
- [ ] https://github.com/WordPress/gutenberg/issues/35607
- [x] https://github.com/WordPress/gutenberg/issues/35525
- [x] https://github.com/WordPress/gutenberg/issues/36084
- [x] https://github.com/WordPress/gutenberg/pull/33217
- [x] https://github.com/WordPress/gutenberg/issues/26901 https://github.com/WordPress/gutenberg/pull/35593
- [x] https://github.com/WordPress/gutenberg/issues/34648
- [x] https://github.com/WordPress/gutenberg/issues/35522
- [x] https://github.com/WordPress/gutenberg/issues/26865
- [x] https://github.com/WordPress/gutenberg/issues/35732

**Nice to have**
- [ ] https://github.com/WordPress/gutenberg/issues/35680
- [ ] https://github.com/WordPress/gutenberg/issues/4543 https://github.com/WordPress/gutenberg/issues/27075
- [ ] https://github.com/WordPress/gutenberg/issues/35591
- [ ] https://github.com/WordPress/gutenberg/issues/35364
- [ ] https://github.com/WordPress/gutenberg/issues/35267
- [ ] https://github.com/WordPress/gutenberg/issues/35524
- [ ] https://github.com/WordPress/gutenberg/issues/34762
- [ ] https://github.com/WordPress/gutenberg/issues/35558
- [ ] https://github.com/WordPress/gutenberg/issues/12997 https://github.com/WordPress/gutenberg/pull/31823 
- [ ] https://github.com/WordPress/gutenberg/issues/35735
- [ ] https://github.com/WordPress/gutenberg/issues/29167
- [ ] https://github.com/WordPress/gutenberg/issues/31815
- [x] https://github.com/WordPress/gutenberg/issues/35934 (Will not be included)
- [x] https://github.com/WordPress/gutenberg/issues/34783

Some of these are already associated to issues in this repo. It would be great to get more folks contributing to these issues.

**Comment by Mamaduka** [comment]
The `gutenberg#35551` issue is listed twice here.

**Comment by aristath** [comment]
https://github.com/WordPress/gutenberg/issues/35591 should also be added to the list above. We need the webfonts API in core & Gutenberg in order to properly implement it in the theme 👍

**Comment by tomjn** [comment]
is there an issue for i18n? I can't find anything for text localisation other than the patterns PR which is a short term workaround

**Comment by tomjn** [comment]
I've created https://github.com/WordPress/gutenberg/issues/36061 to discuss text i18n as well as a general block i18n proposal

**Comment by carolinan** [comment]
Overlay menu can't be closed when "justify right" is used.
https://github.com/WordPress/gutenberg/issues/36102

**Comment by jasmussen** [comment]
That overlay menu issue should be fixed by https://github.com/WordPress/gutenberg/pull/36105.

**Comment by carolinan** [comment]
Post title overflow: https://github.com/WordPress/gutenberg/pull/35703

**Comment by ndiego** [comment]
I would like to propose that https://github.com/WordPress/gutenberg/issues/35267 gets bumped to Must Have. The title of the ticket is a bit too simplistic, this issue actually nullifies any margin settings set in theme.json if `blockGap` is enabled. It's because the following CSS is so specific. While it may not be impacting the theme currently, it will once the public starts "playing" with it. 

![image](https://user-images.githubusercontent.com/4832319/140660826-9f50d49d-eafa-45de-be0f-ca94cf88c50d.png)

**Comment by kjellr** [comment]
> The title of the ticket is a bit too simplistic, this issue actually nullifies any margin settings set in theme.json if blockGap is enabled.

Would you mind sharing this feedback in that ticket? The way we get around this in the theme currently is just by specifying a `blockGap` that is generally compatible with paragraph blocks. But there are a few minor circumstances where that smaller `blockGap` isn't actually ideal. 

I'm not 100% certain about it being a must-have (for this theme at least), but since this is overwriting margin values, I think it's very reasonably a bugfix that should make it into 5.9.

**Comment by ndiego** [comment]
> Would you mind sharing this feedback in that ticket? The way we get around this in the theme currently is just by specifying a blockGap that is generally compatible with paragraph blocks. But there are a few minor circumstances where that smaller blockGap isn't actually ideal.

For sure!

**Comment by jffng** [comment]
Closing this now that the theme is added in 5.9.
