### ISSUE TITLE
Header Patterns: Followup Fixes

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#89]
Following up from #74, there are a few header patterns with unfortunate responsive behavior. I'm creating this issue so that we can continue to track the issues: 

## Header with Tagline

- [ ] This wraps poorly on small screens. ([Screenshot](https://cloudup.com/cxBvFm2Oj3V))

## Text-only Header with Tagline

- [ ] This wraps poorly on small screens. ([Screenshot](https://cloudup.com/cz_z0CveuCt))

## Text-only Header with Tagline and all-caps Title

- [ ] This wraps poorly on small screens. ([Screenshot](https://cloudup.com/c4mv-0BEeLj))

## Header with centered Logo

- [ ] This wraps poorly on small screens. [(GIF)](https://cloudup.com/ciCs3nzlqFN)

## Header with centered Logo in Navigation

- [ ] The site logo disappears on smaller screens. ([Screenshot](https://cloudup.com/c-krv3vU4u7))
- [ ] The layout of the expanded menu looks weird. ([Screenshot](https://cloudup.com/cBDKpdI0Fbz))
- [ ] Depending on the number/length of menu items, the logo is not necessarily located in the exact center. ([Screenshot](https://cloudup.com/cZzkpra6jFl))

## Centered title with Navigation and Social Links Header

- [ ] The items wrap oddly on small screens. ([Screenshot](https://cloudup.com/c91b-Oh1-oD))
- [ ] The navigation items start stacking in a weird way on medium breakpoints. ([Screenshot](https://cloudup.com/cq9BAkOnkXk))

## Title and Button Header

- [x] This one is supposed to have the hamburger icon visible by default on all breakpoints. Requires a resolution to https://github.com/WordPress/gutenberg/issues/34783.

**Comment by kjellr** [comment]
>  This wraps poorly on small screens

^ Regarding all of these bugs: Now that we've gone through all the trouble of getting https://github.com/WordPress/gutenberg/pull/36003 merged, I'm finding more use cases where these look better without that control. For example, take this example with a bunch of menu items and a long tagline.

Here is is normally: 

Desktop|Mobile
---|---
<img width="1039" alt="Screen Shot 2021-11-02 at 3 54 16 PM" src="https://user-images.githubusercontent.com/1202812/139944667-68aeeecf-f3f6-47ba-adc4-8a79066a0a13.png">|<img width="333" alt="Screen Shot 2021-11-02 at 4 10 33 PM" src="https://user-images.githubusercontent.com/1202812/139944937-e8c3c780-a9a2-4aa2-b984-560dad097aae.png">


And here it is with flex-wrap disabled: 

Desktop|Mobile
---|---
<img width="1066" alt="Screen Shot 2021-11-02 at 3 55 17 PM" src="https://user-images.githubusercontent.com/1202812/139942991-27fefbcb-d1fe-4283-8933-e22d37f381bd.png">|<img width="331" alt="Screen Shot 2021-11-02 at 4 10 46 PM" src="https://user-images.githubusercontent.com/1202812/139945052-e555c310-bc6c-4ad1-a0b5-32ee613c820d.png">

The second option here looks better on mobile, but way worse on desktop. I'm feeling a bit foolish here because I can't find a single example where the `flex-wrap` control "just works" across all breakpoints and makes these more robust. 

It looked promising initially, and solved some of the mobile issues, but it creates more issues on desktop than I think it's worth. I think we might end up being better off without using it? 😕

cc @jasmussen, would you mind trying this out a bit too? I'm interested in your opinion.

**Comment by jasmussen** [comment]
Took it for a spin, and for simple short cases, things look good with and without. This one wraps:
![before](https://user-images.githubusercontent.com/1204802/140030924-860b0709-19cd-4715-a058-fc046caa921d.gif)

This one doesn't wrap:

![after](https://user-images.githubusercontent.com/1204802/140030952-b39c825f-a757-48ff-84a8-0e66186226a9.gif)

It's when the flex containers grow very big that the problems appear. This is with wrappig disallowed:
<img width="1095" alt="Screenshot 2021-11-03 at 09 44 09" src="https://user-images.githubusercontent.com/1204802/140031027-aa6e9ddc-a561-4d38-a5c5-4a3ae588119e.png">

This is with wrapping allowed (the previous default right?)
<img width="1074" alt="Screenshot 2021-11-03 at 09 44 18" src="https://user-images.githubusercontent.com/1204802/140031053-b0dfe50f-5431-466f-9a05-09bd1d8d5ece.png">

In that particular case, the latter is better. 

It's tricky, because on one hand, the fact that you can toggle between those options is in and of itself an argument for _having_ the control, to be able to pick what works best. On the other hand, it's going to be hard for anyone but webdesigners to intuit that allowing or disallowing wrapping is going to be the problem solver in either case. 

Which means we might want to look at increasing our confidence level that the control as we added it actually does benefit at least some patterns — that there are some designs we couldn't have accomplished otherwise. If we can find those, we can probably keep the control and manage its prominence by hiding the control in the tools panel.

Otherwise, we might want to revert the control to simplify things, and start to think of other ways to let those layouts have built-in intrinsic responsiveness. For example, [the grid based behaviors](https://codepen.io/joen/pen/wvJMdGr) outlined here might could potentially be enabled by default for blocks that have layout. What do you think? I do realize that would recast this as a future feature — but given the beautiful patterns you've built work well today, and would work even better in the future, that might be fine?

**Comment by kjellr** [comment]
> Which means we might want to look at increasing our confidence level that the control as we added it actually does benefit at least some patterns — that there are some designs we couldn't have accomplished otherwise. If we can find those, we can probably keep the control and manage its prominence by hiding the control in the tools panel.

I spent a bit of time thinking about this, and I believe you've found one of those examples already: 

![](https://user-images.githubusercontent.com/1204802/140030952-b39c825f-a757-48ff-84a8-0e66186226a9.gif)

This will be great for many sites, and wouldn't be possible without the control. I'm still undecided about whether or not we should use it for our patterns here, but I do feel that the tool has worth. That's good enough for the 11.9 feature freeze, and we can reconsider its appearance in the UI later on in the betas if we feel strongly about it.

**Comment by kjellr** [comment]
I'm going to close this one for now. If there are specific issues with these patterns to address, we can open up [new individual Trac issues](https://core.trac.wordpress.org/newticket?component=Bundled+Theme). Thanks!
